import DS from "ember-data";

export default DS.Model.extend({
  id_venue: DS.attr('string'),
  gender: DS.attr('string'),
  email: DS.attr('string'),
  release: DS.attr('string'),
  notes: DS.attr('string'),
  createdAt: DS.attr('string'),
  updatedAt: DS.attr('string'),
  showDate: DS.attr('string'),
  firstName: DS.attr('string'),
  lastName: DS.attr('string'),
  firstNameTwo: DS.attr('string'),
  lastNameTwo: DS.attr('string'),
  firstNameThree: DS.attr('string'),
  lastNameThree: DS.attr('string'),
  firstNameFour: DS.attr('string'),
  lastNameFour: DS.attr('string'),
  childP: DS.attr('string'),
  homeTown: DS.attr('string'),
  homeState: DS.attr('string'),
  subjectIdOne: DS.attr('string'),
  subjectIdTwo: DS.attr('string'),
  subjectIdThree: DS.attr('string'),
  cardText: DS.attr('string'),
  cardImage: DS.attr('string'),
  enteredDate: DS.attr('string'),
});
